### ISSUE TITLE
1.14.0 breaks existing pipelines

### ISSUE THREAD

**Issue by flyandi** [grpc-ecosystem/grpc-gateway#1154]
The latest 1.14 update has moved many previous accessible API's behind closed doors which in our case fails our entire auto-gen-swagger pipeline and can't ship anything without removing any modules using your dependencies. 

We use a probably very widely used module - https://github.com/elliots/protoc-gen-twirp_swagger

This move is creating a lot of headache for many people even those API's were never intended to be public - they are kind of now. I am arguing to bring those back and work with the community and associated major module contributor as well checking the dependency tree here in GitHub before making such drastic changes to a critical piece.

Thanks,
Andy

**Comment by johanbrandhorst** [comment]
Hi, thanks for raising this issue. We knew the change might break some users, so sorry about that. I hope you can appreciate why we took the steps we did.

It looks like that module imports `protoc-gen-grpc-gateway/descriptor` and `protoc-gen-grpc-gateway/generator`. I'll move those back into the public API. Let me know if I missed any.

You mention checking the dependency tree in GitHub, what do you mean by that? We're happy to bring back anything that's genuinely useful or required for things that are very popular or hard to change, but we'd still like to keep as much internal as possible. The end goal here is to increase compatibility, by allowing us to use https://golang.org/x/exp/cmd/gorelease.

**Comment by johanbrandhorst** [comment]
I've opened https://github.com/grpc-ecosystem/grpc-gateway/pull/1155, could you verify that this fixes your issue please? Let me know if you need any other packages moved.

**Comment by johanbrandhorst** [comment]
I've released 1.14.1 with this change. Please confirm it is fixed.

**Comment by flyandi** [comment]
Thank you so much. We are in good shape again.

**Comment by karel-3d** [comment]
@flyandi the tests are still broken, they depend on `github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/httprule` (also mentioned by someone in the original thread)
