### ISSUE TITLE
Swagger: JSON definitions aren't CamelCased

### ISSUE THREAD

**Issue by utrack** [grpc-ecosystem/grpc-gateway#375]
Example:
```
message Foo {
  string bar_baz = 1;
}
```

Go generator generates CamelCased JSON field `json="barBaz,omitempty"`, but gen-swagger takes raw name (`bar_baz`).

https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L1781

**Comment by keekun** [comment]
same problem.

I think the `f.GetName()` in following code should be `f.GetJsonName()`.

```go
schema.Properties = append(schema.Properties, keyVal{f.GetName(), fieldValue})
```

https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go#L186

**Comment by achew22** [comment]
There has been a lot of work on the swagger definitions since this was filed and I think it's likely that this is fixed. If you have more issues please reopen/file a new issue.

**Comment by alexleigh** [comment]
This is still an issue. f.GetName() is still being used, resulting in snake_case names rather than camelCase names in the generated swagger definitions.

**Comment by achew22** [comment]
@alexleigh, looks like it is. Would you mind contributing a patch and helping out the community? It would be a great starter to get into the project. Just remember to run `make examples` afterward to ensure update the goldens.

**Comment by johanbrandhorst** [comment]
I think we want to fix this for v2, if it's still an issue.

**Comment by johanbrandhorst** [comment]
Fixed in https://github.com/grpc-ecosystem/grpc-gateway/pull/1376
